/**
 * 错误码定义
 * 格式：模块(2位) + 具体错误(3位)
 */
export const ERROR_CODES = {
  // 通用错误 (00xxx)
  SUCCESS: 0,
  UNKNOWN_ERROR: 500,
  PARAMS_ERROR: 400,
  
  // 认证错误 (10xxx)
  AUTH_TOKEN_INVALID: 10001,
  AUTH_TOKEN_EXPIRED: 10002,
  AUTH_WECHAT_LOGIN_FAILED: 10003,
  
  // 用户错误 (20xxx)
  USER_NOT_FOUND: 20001,
  USER_ALREADY_EXISTS: 20002,
  
  // 游戏错误 (30xxx)
  GAME_NOT_FOUND: 30001,
  GAME_ALREADY_STARTED: 30002,
  GAME_ALREADY_FINISHED: 30003,
  GAME_INVALID_MOVE: 30004,
  GAME_NOT_YOUR_TURN: 30005,
  GAME_POSITION_OCCUPIED: 30006,
  
  // 房间错误 (40xxx)
  ROOM_NOT_FOUND: 40001,
  ROOM_FULL: 40002,
  ROOM_PASSWORD_ERROR: 40003,
  ROOM_EXPIRED: 40004,
  
  // 匹配错误 (50xxx)
  MATCH_TIMEOUT: 50001,
  MATCH_ALREADY_IN_QUEUE: 50002,
} as const;

/**
 * 错误消息映射
 */
export const ERROR_MESSAGES: Record<number, string> = {
  [ERROR_CODES.SUCCESS]: '成功',
  [ERROR_CODES.UNKNOWN_ERROR]: '未知错误',
  [ERROR_CODES.PARAMS_ERROR]: '参数错误',
  
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 'Token无效',
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Token已过期',
  [ERROR_CODES.AUTH_WECHAT_LOGIN_FAILED]: '微信登录失败',
  
  [ERROR_CODES.USER_NOT_FOUND]: '用户不存在',
  [ERROR_CODES.USER_ALREADY_EXISTS]: '用户已存在',
  
  [ERROR_CODES.GAME_NOT_FOUND]: '游戏不存在',
  [ERROR_CODES.GAME_ALREADY_STARTED]: '游戏已开始',
  [ERROR_CODES.GAME_ALREADY_FINISHED]: '游戏已结束',
  [ERROR_CODES.GAME_INVALID_MOVE]: '无效的落子',
  [ERROR_CODES.GAME_NOT_YOUR_TURN]: '还没轮到你',
  [ERROR_CODES.GAME_POSITION_OCCUPIED]: '该位置已被占用',
  
  [ERROR_CODES.ROOM_NOT_FOUND]: '房间不存在',
  [ERROR_CODES.ROOM_FULL]: '房间已满',
  [ERROR_CODES.ROOM_PASSWORD_ERROR]: '房间密码错误',
  [ERROR_CODES.ROOM_EXPIRED]: '房间已过期',
  
  [ERROR_CODES.MATCH_TIMEOUT]: '匹配超时',
  [ERROR_CODES.MATCH_ALREADY_IN_QUEUE]: '已在匹配队列中',
};

